export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const PRODUCT_ERROR='PRODUCT_ERROR';
export const GET_USERS='GET_USERS';
export const USER_ERROR='USER_ERROR';
export const GET_PRODUCT_WISHLIST='GET_PRODUCT_WISHLIST';
export const GET_WISHLISTS='GET_WISHLISTS';
export const REMOVE_WISHLIST='REMOVE_WISHLIST';
export const DELETE_USER='DELETE_USER';
export const ADD_WISHLIST='ADD_WISHLIST';
export const GET_PRODUCT_PANIER='GET_PRODUCT_PANIER';
export const WISHLIST_ERROR='WISHLIST_ERROR';
export const GET_PANIER='GET_PANIER';
export const REMOVE_PANIER='REMOVE_PANIER';
export const ADD_TO_PANIER='ADD_TO_PANIER';
export const PANIER_ERROR='PANIER_ERROR';
export const GET_COMMENT='GET_COMMENT';
export const ADD_COMMENT='ADD_COMMENT';
export const REMOVE_COMMENT='REMOVE_COMMENT';
export const COMMENT_ERROR='COMMENT_ERROR';
export const PUT_USER='PUT_USER';
export const CHANGE_PASSWORD='CHANGE_PASSWORD';
export const FORGET_PASSWORD='FORGET_PASSWORD';
export const GET_PROPOSITIONS='GET_PROPOSITIONS';
export const PROPOSITION_ERROR='PROPOSITION_ERROR';
export const DELETE_PROPOSITION='DELETE_PROPOSITION';
export const ADD_PROPOSITION='ADD_PROPOSITION';
export const GET_ORDER='GET_ORDER';
export const GET_PROPOSITION='GET_PROPOSITION';
export const ADD_ORDER='ADD_ORDER';
export const REMOVE_ORDER='REMOVE_ORDER';
export const ORDER_ERROR='ORDER_ERROR';

export const GET_ADDRESS='GET_ADDRESS';
export const REQUEST_ORGANISATION='REQUEST_ORGANISATION';

export const REQUEST_DELIVERY='REQUEST_DELIVERY';
export const CONFIRME_REQUEST='CONFIRME_REQUEST';
export const GET_REQUEST_ORGANISATION='GET_REQUEST_ORGANISATION';
export const GET_REQUEST_DILEVRY='GET_REQUEST_DILEVRY';
export const ACCEPT_Request_ORGANISATION='ACCEPT_Request_ORGANISATION';
export const REQUEST_ERROR='REQUEST_ERROR';
export const ACCEPT_Request_DELIVERY='ACCEPT_Request_DELIVERY';
export const BLOCK_USER='BLOCK_USER';

export const UNBLOCK_USER='UNBLOCK_USER';
export const GET_MYPRODUCT='GET_MYPRODUCT';
export const PROFILE_ERROR='PROFILE_ERROR';
export const GET_ORDER_WITHOUT_DELIVERY= 'GET_ORDER_WITHOUT_DELIVERY'
export const RESERVEORDER= 'RESERVEORDER'
export const CHANGE_STATE= 'CHANGE_STATE'
export const MY_ORDERS_DELIVERY= 'MY_ORDERS_DELIVERY'
export const GET_MY_EXCHANGE_PRODUCTS= 'GET_MY_EXCHANGE_PRODUCTS'
export const ADD_ORDER_Exchange= 'ADD_ORDER_Exchange'
export const GET_OPINIONS="GET_OPINIONS"
export const SAVE_MESSAGE = 'save_message';
export const ADD_REP="ADD_REP"
export const GET_SEARCH="GET_SEARCH"
export const GET_PROFILE="GET_PROFILE"
export const GET_MYPRODUCT_USER="GET_MYPRODUCT_USER"
export const CONVERSATION="CONVERSATION"
export const RESERVEPRODUCT="RESERVEPRODUCT"
export const P_ERROR="P_ERROR"
export const GET_SEARCH_PRODUCT="GET_SEARCH_PRODUCT"
export const RECOMMENDED_SYS="RECOMMENDED_SYS"












